### PR TITLE
Added the ability to train DNNClassifier with V1 Optimizer

### PR DESCRIPTION
**Pull request by Anmol-Sharma**
For the examples mentioned [here](https://www.tensorflow.org/api_docs/python/tf/estimator/DNNClassifier) for DNN Classifier, there was an error when trying to train the model with with an optimizer of type `tf.compat.v1.train.Optimizer`.

This issue was primarily raised in the tensorflow repository : [46342](https://github.com/tensorflow/tensorflow/issues/46342). Please refer to this, for further details.

This is a fix for the issue raised there.

### CODE REVIEW

**Comment by zhjunqin** [comment]
I find same issue when use head api in estimator.

```
  File "/usr/local/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/head/multi_head.py", line 491, in create_estimator_spec
    train_op = base_head.create_estimator_spec_train_op(
  File "/usr/local/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/head/base_head.py", line 904, in create_estimator_spec_train_op
    validate_v2_optimizer(optimizer)
  File "/usr/local/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/head/base_head.py", line 667, in validate_v2_optimizer
    raise ValueError(
ValueError: The given optimizer is not a tf.keras.optimizers.Optimizer instance. Given: <tensorflow.python.training.adagrad.AdagradOptimizer object at 0x7f4f8d11d070>
```
In `base_head.py`
```
  with ops.name_scope(''):  # Reset all previous name_scope.
    # Add training as the name_scope to be compatible with Keras.
    with ops.name_scope('training'):
      if optimizer is not None:
        if train_op_fn is not None:
          raise ValueError('train_op_fn and optimizer cannot both be set.')
        validate_v2_optimizer(optimizer)   # => this only allowed v2 optimizer
        validate_trainable_variables(trainable_variables)
        # Scale loss by number of replicas.
```

hope this PR could be merged.

**Comment by zhjunqin** [comment]
I think It is better to change  in fucntion `create_estimator_spec_train_op` to 

```
          if isinstance(optimizer, optimizer_v2.OptimizerV2):
            base_head.validate_trainable_variables(trainable_variables)
            # optimizer_v2.get_updates always returns a list, and the first
            # element is the train_op.
            train_op = optimizer.get_updates(
                loss, trainable_variables)[0]
          else:
            train_op = optimizer.minimize(
                loss,
                global_step=training_util.get_global_step())
```

please refer to  https://github.com/tensorflow/estimator/blob/r1.14/tensorflow_estimator/python/estimator/head/multi_head.py#L427

**Review by mihaimaruseac — DISMISSED** [review]

**Comment by mihaimaruseac** [comment]
Can you please resolve conflicts?

**Comment by Anmol-Sharma** [comment]
> Can you please resolve conflicts?

Hello, sorry for the late reply. I couldn't find time earlier. I have fixed the merge conflicts in the latest commit [Here](https://github.com/Anmol-Sharma/estimator/commit/d2d9dfaff4136a8fefc7eb2da93accbbeafef4bf) and checked locally on my system and it works for both v1 and v2 optimizers.

Please verify on your end.

**Comment by mihaimaruseac** [comment]
Sorry, was OOO Friday and now I see there is a new conflict.

**Comment by Anmol-Sharma** [comment]
> Sorry, was OOO Friday and now I see there is a new conflict.

Hello,

So i just rebased the changes from the master to my fork and a lot of changes have been introduced to my original fork. I think it will be better if I simply create a new pull request from the existing master and submit a new PR, as there are too many commits from other authors which will become part of this PR, which is not ideal.

So I think I will issue a new PR with the changes I proposed and it should then be easier to review and merge and I will mention that here.

**Pull request closed without merging**
