### PR TITLE
fix get_hooks_from_the_first_device

### PR DESCRIPTION
**Pull request by CheukNgai**
Here i create a cifar10_ResNet Model and run the model in a distribution mode and find the error "the Estimator has no attribute named _distribution" and i can't get the get_hooks, so i modify _distribution to _train_distribution. The model is attached in the file for testing.

Type this command:
python cifar10_main.py --data-dir=./cifar-10-data --job-dir=./model_dir/ --num-gpus=0 --train-steps=1000
[ResNet_Cifar10.zip](https://github.com/tensorflow/estimator/files/2495319/ResNet_Cifar10.zip)

### CODE REVIEW

**Comment by guptapriya** [comment]
Thank you for fixing, @CheukNgai . Looks good to me.

**Comment by guptapriya** [comment]
This will fix issue https://github.com/tensorflow/tensorflow/issues/23232 .

**Comment by guptapriya** [comment]
@case540 can you help get this PR merged? I am not sure what the process for this new repo is.

**Comment by case540** [comment]
Thanks for not merging this directly! I need to lock down master branch similar to main TensorFlow repo. I think we should be able to use the same ready-to-pull label to merge this through our internal process.

**Comment by case540** [comment]
ok, seems there is still something I have to set up to get this workflow set up. Please DONT merge this before this is set up.

**Comment by case540** [comment]
Ok, this is going through our internal review system now.

**Comment by guptapriya** [comment]
Thanks @case540

**Pull request merged**
