### PR TITLE
Add bazelrc and gitignore

### PR DESCRIPTION
**Pull request by perfinion**
Add .bazelrc that try-import's .bazelrc.user for user-specific options.
Also add python generated and editor files to .gitignore, mainly taken
from tensorflow's gitignore.

Signed-off-by: Jason Zaman <jason@perfinion.com>

### CODE REVIEW

**Comment by karmel** [comment]
Thanks @perfinion . I am fine with this-- @gunan , can you just confirm that this won't create any upstream problems when we pull into TF proper?

**Comment by gunan** [comment]
AFAICT this should be OK.

**Comment by mihaimaruseac** [comment]
This one has some issues importing, will revisit later today

**Comment by mihaimaruseac** [comment]
Still failing, will probably need to redo, but let's wait for the others to merge first.

**Comment by mihaimaruseac** [comment]
Needs some internal changes first, but I hope to get this merged in the next hour

**Pull request merged**
