### PR TITLE
_save_first_checkpoint in tf.keras.estimator.model_to_estimator should only be called on chief

### PR DESCRIPTION
**Pull request by sharkdtu**
when run in distribute mode, it will cause race condition of `_save_first_checkpoint`. So, we should judge if its task_type is chief.

### CODE REVIEW

**Comment by gbaned** [comment]
@sharkdtu Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@sharkdtu Can you please resolve conflicts? Thanks!

**Comment by gbaned** [comment]
@sharkdtu Can you please resolve conflicts? Thanks!

**Comment by sharkdtu** [comment]
> @sharkdtu Can you please resolve conflicts? Thanks!

done

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Would be great if you can also provide a test case for this.

Estimator is in maintenance mode and we should only update this code if covered by tests.

**Comment by gbaned** [comment]
Hi @sharkdtu Can you please check @mihaimaruseac's comments and resolve conflicts?. Thank you!

**Comment by mihaimaruseac** [comment]
Closing stale PR. Note that Estimator is no longer active, currently it's only updated as needed to fully deprecate from TF.

**Pull request closed without merging**
