### PR TITLE
Skip temp directory while saving checkpoints and SavedModels on S3

### PR DESCRIPTION
**Pull request by rahul003**
This PR is to be reviewed in conjunction with https://github.com/tensorflow/tensorflow/pull/36388 

S3 supports an eventual consistency model, which does not work like a regular file system. This means that many operations currently in the s3 file system crash now and then because the conditions it expects are not satisfied by S3. 

When saving Checkpoints and SavedModels, there is also the use of a temp directory where all files are uploaded and then moved to the final location. This is even more problematic given S3's eventual consistency model. This sequence of operations involves the writing to temp location, listing of files in temp location, copying each file from this temp location to final location, and deleting the temp location. There are multiple issues users have experienced because of this sequence. When listing files in temp directory, in some cases not all files show up in the list. This causes some files to not be copied. While deleting directory, there is another listing of all files in the directory. Again this list may be inconsistent and the deleting of directory fails. So the usage of such temp directory has been bypassed for S3 file system.

The change has been implemented by introducing a has_atomic_move method for the filesystem and exposing it to python similar to how IsDirectory works. This method needs to be used multiple places both in python and CPP. By default for any file system other than S3, it returns False, which allows us to skip the usage of temp locations.

### CODE REVIEW

**Comment by rahul003** [comment]
The last time I'd created a PR I was told to add a test for this. Any suggestions on how to add a test for this? Right now the way I know of is to monitor the logs from S3 file system. In the linked PR I was told to not create a test which uses S3 because that fails in Google's internal system as TF is not built with TF there.

**Comment by mihaimaruseac** [comment]
Given the fact that this issue pops up in all projects dependent on TF, I think it would be better to stop merging these PRs for now and instead get a RFC proposal that has a design for the entire solution. Once that is approved, we can start accepting PRs faster.

Please submit a RFC at https://github.com/tensorflow/community, I can be the sponsor (tag me)

Also, while writing that, let's take into consideration [the modular filesystem API](https://github.com/tensorflow/community/blob/master/rfcs/20190506-filesystem-plugin-modular-tensorflow.md) which is currently [WIP](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/c/experimental/filesystem)

**Comment by rahul003** [comment]
Ok thanks for the reference. Will look into that and create an RFC.

**Comment by gbaned** [comment]
@rahul003 Any update on this PR? Please. Thanks!

**Comment by rahul003** [comment]
This is no longer needed as S3 is now strongly consistent.

**Pull request closed without merging**
