### PR TITLE
copy of  input_receiver.features

### PR DESCRIPTION
**Pull request by wu-yy**
deepcopy of  input_receiver.features avoid changing  input_receiver.features in model_fn

### CODE REVIEW

**Comment by k-w-w** [comment]
Thanks for the PR! 

I think this counts as a shallow copy, since the values aren't being copied in the new dict. You could replace the loop and use: `copy.copy(input_receiver.features)`

Also, is there an issue associated with this change? Typically, the `input_receiver_fn` produces a new features dict that isn't used anywhere else, which is why modifications to it would be generally acceptable. (but for code cleanliness, I agree that making a copy before passing it to the model function is better).

**Comment by wu-yy** [comment]
@k-w-w  thanks for your reply， We encountered this problem because the incoming features were modified in model_fn， so, the `placeholder` which is not savdemodel is not matched the `input_receiver_fn`.
I will change the PR and use deep copy.

**Comment by gbaned** [comment]
Hi @k-w-w Can you please review this PR ? Thank you!

**Review by mihaimaruseac — APPROVED** [review]
Approving, but note that Estimator is no longer active, currently it's only updated as needed to fully deprecate from TF.

**Comment by mihaimaruseac** [comment]
No more updates to Estimator, except to ensure compat with TF releases, when needed

**Pull request closed without merging**
